### ISSUE TITLE
Intero (stack ghci) failure with a location field in stack.yaml

### ISSUE THREAD

**Issue by PierreR** [commercialhaskell/intero#328]
Inside a project, as soon as I add a location line to `stack.yaml`, intero would fail even if I `stack clean` and retry booting `intero`:
```
resolver: lts-7.11
extra-deps:
- turtle-1.3.0
- optparse-applicative-0.13.0.0
packages:
- location:
    git: https://github.com/sdiehl/protolude.git
    commit: dac4888f6164a7075e259e0ed2f6b7c9737ddb81
```
The error is :
```
→   stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-build --no-load --ghci-options -odir=/home/vagrant/projects/cicd/shell/.stack-work/intero/intero1168FGH --ghci-options -hidir=/home/vagrant/projects/cicd/shell/.stack-work/intero/intero1168FGH cicd-shell

The following target packages were not found: cicd-shell
```
`cicd-shell` is the name of the project.

Using the exact same configuration, `stack install` works perfectly.

As soon as I remove the location line, `intero` would boot normally again.
