### ISSUE TITLE
Intero with nix error

### ISSUE THREAD

**Issue by bch29** [commercialhaskell/intero#466]
I'm on Arch Linux. I'm using stack with nix to build my project. It builds with stack just fine. But when I open it in Emacs I get

```
error: file ‘nixpkgs’ was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:14
```

Here's my `stack.yaml`:

```yaml
resolver: nightly-2017-09-01

nix:
  enable: true
  packages:
    - postgresql
    - zlib
    - binutils
packages:
- .
extra-deps: []
flags: {}
extra-package-dbs: []
```

I've tried using versions of stack installed with both nix-env and pacman, both produced the same error. My Emacs `intero` package is up to date.
